# Generated by Django 4.2.4 on 2023-08-24 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orderApis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
